# Generated by Django 5.0.6 on 2024-08-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0002_ticket_npersons_ticket_total_price_venue_gmaplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
