# Generated by Django 5.0.6 on 2024-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0003_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='statusreason',
            field=models.TextField(default='Admin waiting to approve'),
        ),
    ]
