# Generated by Django 5.0.6 on 2024-09-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0006_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manage_app.organizer')),
            ],
        ),
    ]
