# Generated by Django 5.0.6 on 2024-09-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0008_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_fname', models.CharField(max_length=20)),
                ('so_email', models.EmailField(max_length=254)),
                ('so_phone', models.CharField(max_length=15)),
                ('so_address', models.TextField()),
                ('so_district', models.CharField(max_length=20)),
                ('so_pincode', models.CharField(max_length=6)),
                ('add_message', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150)),
                ('type', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=150, null=True)),
                ('order_id', models.CharField(max_length=150, unique=True)),
                ('tracking_no', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manage_app.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manage_app.organizer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manage_app.user')),
            ],
        ),
    ]
