# Generated by Django 5.0.6 on 2024-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0010_order_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancelticket',
            field=models.BooleanField(default=False),
        ),
    ]
