# Generated by Django 5.0.6 on 2024-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0011_ticket_cancelticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tempcancellable',
            field=models.BooleanField(default=True),
        ),
    ]
