# Generated by Django 5.0.6 on 2024-10-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0012_ticket_tempcancellable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='isrefunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refunddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refundid',
            field=models.CharField(default='nil', max_length=150),
        ),
    ]
