# Generated by Django 5.0.6 on 2024-10-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage_app', '0013_ticket_isrefunded_ticket_refunddate_ticket_refundid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isrefunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='refunddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='refundid',
            field=models.CharField(default='nil', max_length=150),
        ),
    ]
